default:
  outputs:
    dev:
      dataset: uber_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: uber-data-project-433508
      threads: 5
      type: bigquery
  target: dev
uber_data:
  outputs:
    dev:
      dataset: uber_data
      keyfile: /usr/local/airflow/include/gcp/service_account.json
      location: US
      method: service-account
      project: uber-data-project-433508
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dev
